# ML Practical Lab 1

## What is supervised learning? What is unsupervised learning? What is reinforcement learning?

- **Supervised learning**
    - Training data contains the preferred answers (target variable)
    - **Goal**: to predict the future by learning from a model of labeled training data
    - Examples
        - Linear Regression
        - Classification 
- **Unsupervised learning**
    - Starts with training data without labels
    - **Goal** is to group unlabelled data based on some connections (clustering)
    - Examples:
        - Clustering
    	- Unsupervised Anomaly Detection   
- **Reinforcement learning**
    - Can observe the environment
    - Select and perform actions
    - Get rewards and penalties in return
    - learn by itself what is the best strategy to get the most reward over time

### Differences

**Supervised Learning** - labelled data, have feedback, predict future/outcome

**Unsupervised Learning** - no labels, no feedback, find hidden structures in data

**Reinforcement Learning** - no labels, reward system, learn from series of actions

## Write a program which asks users to enter five numbers, and then prints out the largest of the five numbers

In [1]:
  
def get_largest_number(numbers):
    largest = numbers[0]
    for num in numbers:
        if num > largest:
            largest = num
    return largest

def main():
    try:
        numbers = []
        for i in range(5):
            num = float(input(f'Enter number {i+1}: '))
            numbers.append(num)
            
        Lnum = get_largest_number(numbers)
        print(f'The largest number is: {Lnum}')
        
    except ValueError:
        print("Invalid input. Please enter valid numbers.")
        
        
if __name__ == "__main__":
    main()


Enter number 1:  9
Enter number 2:  23
Enter number 3:  4
Enter number 4:  5
Enter number 5:  6


The largest number is: 23.0


## Use NumPy to do the following:
1) Create a 2x3 matrix A with random integers between 0 and 10, print it
2) Create a 3x4 matrix B with random integers between 0 and 3, print it.
3) Calculate A’s transpose, print it
4) Calculate the dot product of A and B, print it

In [2]:
import numpy as np

def create_random_matrix(r,c,min_val,max_val):
    return np.random.randint(min_val,max_val+1, size = (r,c))

def print_matrix(matrix):
    for row in matrix:
        print(row)
        
def main():
    
    # 1. Create 2x3 Matrix A with random integers between 0 and 10
    Arow = 2
    Acol = 3
    Amin_value = 0
    Amax_value = 10
    
    matrix_A = create_random_matrix(Arow,Acol,Amin_value,Amax_value)
    print("Matrix A: ")
    print_matrix(matrix_A)
    
    # 2. Create 3x4 Matrix B with random integers between 0 and 3
    Brow = 3
    Bcol = 4
    Bmin_value = 0
    Bmax_value = 3
    
    matrix_B = create_random_matrix(Brow,Bcol,Bmin_value,Bmax_value)
    print("\nMatrix B: ")
    print_matrix(matrix_B)
    
    # 3. Calculate A's transpose and print it
    matrix_A_transpose = np.transpose(matrix_A)
    print("\nMatrix A's transpose: ")
    print_matrix(matrix_A_transpose)
    
    # 4. Calculate the dot product of A and B
    matrix_dot_product = np.dot(matrix_A, matrix_B)
    print("\nDot product of A and B: ")
    print_matrix(matrix_dot_product)
    
    
    
if __name__ == "__main__":
    main()

Matrix A: 
[ 5 10  4]
[3 8 2]

Matrix B: 
[1 3 3 0]
[2 0 1 0]
[3 3 1 0]

Matrix A's transpose: 
[5 3]
[10  8]
[4 2]

Dot product of A and B: 
[37 27 29  0]
[25 15 19  0]


## Creating Pandas DataFrames
Generate the following table. Create a list, and then create a Panda DataFrames from the list and print it.

|make|model|year|fuel|
|---|---|---|---|
0|Ford|Everest|2016|Diesel|
1|Toyota|Kluger|2005|Petrol|
2|Hyundai|Santa Fe|2010|Diesel
3|Honda|CR-V|2018|Petrol
4|Subaru|Forrester|2017|Petrol

In [3]:
import pandas as pd

d = {'make' : ['Ford','Toyota','Hyundai','Honda','Subaru'],
        'model' : ['Everest','Kluger','Santa Fe','CR-V','Forrester'],
        'year' : [2016,2005,2010,2018,2017],
        'fuel' : ['Diesel','Petrol','Diesel','Petrol','Petrol']
        }

df = pd.DataFrame(d)
print(df)

      make      model  year    fuel
0     Ford    Everest  2016  Diesel
1   Toyota     Kluger  2005  Petrol
2  Hyundai   Santa Fe  2010  Diesel
3    Honda       CR-V  2018  Petrol
4   Subaru  Forrester  2017  Petrol


## Create a DataFrame from external source such as a csv file using the `read_csv('<path>')` function. 

In [4]:
import pandas as pd
cars = pd.read_csv('car_data.csv')
print(cars)


    Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
0        Dealer       Manual      0  
1        Dealer       Manual      0